version: '3.8'

services:
  web:
    image: web:latest
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "4000:5500"
    depends_on:
      - mariadb


  oracle:
    image: container-registry.oracle.com/database/xe:21.3.0
    container_name: oracle-xe
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=ej_pw
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:
  oracle_data: