services:
  work:
    image: work_sql:1.0.7
    ports:
      - "4000:5500"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Development
      # 這行刪掉會不能跑
      - ASPNETCORE_URLS=http://+:5500 
      # Redis 服務所在的主機名稱(container 名稱)
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      redis:
        condition: service_healthy


  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"

    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    # 這行也不能刪，會導致conf沒有被讀到
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_pw", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  mariadb_data:
