services:
  work:
    image: work_sql:1.1.3
    container_name: work
    restart: always
    ports:
      - "4000:5500"
    environment:
      - DB_SERVER=${DB_SERVER}
      - DB_PORT=${DB_PORT}
      - DB_DB=${DB_DB}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5500 
      # Redis 服務所在的主機名稱(container 名稱)
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5500/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s


  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mariadb
    environment: 
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=${DB_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./configs/redis.conf:/usr/local/etc/redis/redis.conf
    # 這行也不能刪，會導致conf沒有被讀到
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_pw", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      ##容器啟動後的前 10 秒屬於寬限期，這段期間內的檢查失敗不會計入失敗次數。
      start_period: 10s

volumes:
  mariadb_data:
    driver: local
