version: '3.8'

services:
  web:
    image: sql:latest
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "4000:5500"
    depends_on:
      - mariadb


  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_DATABASE: tododb
      MYSQL_USER: ej
      MYSQL_PASSWORD: ej_pw
    ports:
      - "3306:3306"

    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
