CREATE DATABASE IF NOT EXISTS DB1;
CREATE DATABASE IF NOT EXISTS DB2;

CREATE USER 'ej'@'%' IDENTIFIED BY 'ej_pw';
GRANT ALL PRIVILEGES ON DB1.* TO 'ej'@'%';
GRANT ALL PRIVILEGES ON DB2.* TO 'ej'@'%';
FLUSH PRIVILEGES;
